import { createFileRoute, Link } from "@tanstack/react-router";
import { Shield, Mail } from "lucide-react";
import { EmailContactLink } from "@/components/EmailContactLink";

type Section = {
  title: string;
  intro?: string[];
  subsections?: { title: string; content: (string | string[])[] }[];
  content?: (string | string[])[];
};

const sections: Section[] = [
  {
    title: "Interpretation and Definitions",
    subsections: [
      {
        title: "Interpretation",
        content: [
          "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
        ],
      },
      {
        title: "Definitions",
        content: [
          "For the purposes of this Privacy Policy:",
          [
            "Account means a unique account created for You to access our Service or parts of our Service.",
            "Affiliate means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.",
            "Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to ShivAryan Infotech Services, Bilaspur, Himachal Pradesh.",
            "Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
            "Country refers to: Himachal Pradesh, India",
            "Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
            "Personal Data is any information that relates to an identified or identifiable individual.",
            "Service refers to the Website.",
            "Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
            "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
            "Website refers to ShivAryan Infotech Services, accessible from https://saispl.com/",
            "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
          ],
        ],
      },
    ],
  },
  {
    title: "Collecting and Using Your Personal Data",
    subsections: [
      {
        title: "Types of Data Collected — Personal Data",
        content: [
          "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
          [
            "Email address",
            "First name and last name",
            "Phone number",
            "Address, State, Province, ZIP/Postal code, City",
            "Usage Data",
          ],
        ],
      },
      {
        title: "Usage Data",
        content: [
          "Usage Data is collected automatically when using the Service.",
          "Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
          "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
          "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
        ],
      },
      {
        title: "Tracking Technologies and Cookies",
        content: [
          "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:",
          [
            "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.",
            "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).",
          ],
          "Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.",
          "We use both Session and Persistent Cookies for the purposes set out below:",
          [
            "Necessary / Essential Cookies (Session, Administered by Us): Essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.",
            "Cookies Policy / Notice Acceptance Cookies (Persistent, Administered by Us): Identify if users have accepted the use of cookies on the Website.",
            "Functionality Cookies (Persistent, Administered by Us): Allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.",
          ],
          "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.",
        ],
      },
      {
        title: "Use of Your Personal Data",
        content: [
          "The Company may use Personal Data for the following purposes:",
          [
            "To provide and maintain our Service, including to monitor the usage of our Service.",
            "To manage Your Account: to manage Your registration as a user of the Service.",
            "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
            "To contact You: by email, telephone calls, SMS, or other equivalent forms of electronic communication, regarding updates or informative communications related to the functionalities, products or contracted services, including security updates.",
            "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
            "To manage Your requests: To attend and manage Your requests to Us.",
            "For business transfers: to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.",
            "For other purposes: such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.",
          ],
          "We may share Your personal information in the following situations:",
          [
            "With Service Providers: to monitor and analyze the use of our Service, to contact You.",
            "For business transfers: in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
            "With Affiliates: in which case we will require those affiliates to honor this Privacy Policy.",
            "With business partners: to offer You certain products, services or promotions.",
            "With other users: when You share personal information or otherwise interact in the public areas with other users.",
            "With Your consent: for any other purpose with Your consent.",
          ],
        ],
      },
      {
        title: "Retention of Your Personal Data",
        content: [
          "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
          "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
        ],
      },
      {
        title: "Transfer of Your Personal Data",
        content: [
          "Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. This information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those in Your jurisdiction.",
          "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
          "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
        ],
      },
      {
        title: "Delete Your Personal Data",
        content: [
          "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
          "Our Service may give You the ability to delete certain information about You from within the Service.",
          "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
          "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
        ],
      },
    ],
  },
  {
    title: "Disclosure of Your Personal Data",
    subsections: [
      {
        title: "Business Transactions",
        content: [
          "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
        ],
      },
      {
        title: "Law enforcement",
        content: [
          "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
        ],
      },
      {
        title: "Other legal requirements",
        content: [
          "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
          [
            "Comply with a legal obligation",
            "Protect and defend the rights or property of the Company",
            "Prevent or investigate possible wrongdoing in connection with the Service",
            "Protect the personal safety of Users of the Service or the public",
            "Protect against legal liability",
          ],
        ],
      },
    ],
  },
  {
    title: "Security of Your Personal Data",
    content: [
      "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
    ],
  },
  {
    title: "Children’s Privacy",
    content: [
      "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
      "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.",
    ],
  },
  {
    title: "Links to Other Websites",
    content: [
      "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.",
      "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
    ],
  },
  {
    title: "Changes to this Privacy Policy",
    content: [
      "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
      "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy.",
      "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
    ],
  },
  {
    title: "Contact Us",
    content: [
      "If you have any questions about this Privacy Policy, You can contact us:",
      ["By email: Help@saispl.com"],
    ],
  },
];

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Shivaryan Infotech" },
      {
        name: "description",
        content:
          "How Shivaryan Infotech collects, uses, and protects personal information across our AI, software, and web development services for clients in India and globally.",
      },
      {
        name: "keywords",
        content:
          "Shivaryan Infotech privacy policy, data protection, GDPR India, AI software privacy",
      },
      { property: "og:title", content: "Privacy Policy — Shivaryan Infotech" },
      {
        property: "og:description",
        content:
          "How Shivaryan Infotech collects, uses, and protects your personal information.",
      },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/privacy" },
      { name: "robots", content: "noindex, follow" },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:title", content: "Privacy Policy — Shivaryan Infotech" },
      { name: "twitter:description", content: "How we collect, use, and protect your personal information." },
    ],
    links: [{ rel: "canonical", href: "/privacy" }],
  }),

  component: Privacy,
});

function renderBlocks(blocks: (string | string[])[]) {
  return blocks.map((block, idx) =>
    Array.isArray(block) ? (
      <ul key={idx} className="list-disc space-y-2 pl-6 marker:text-brand">
        {block.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    ) : (
      <p key={idx}>{block}</p>
    ),
  );
}

function Privacy() {
  return (
    <div className="relative">
      {/* Hero */}
      <section className="relative overflow-hidden pb-12 pt-24 md:pt-32">
        <div
          className="absolute inset-0"
          style={{
            background:
              "radial-gradient(ellipse 80% 50% at 50% -10%, rgba(0,185,241,0.08), transparent)",
          }}
        />
        <div className="relative z-10 mx-auto max-w-3xl px-4 text-center sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl md:text-6xl">
            Privacy <span className="text-brand">Policy</span>
          </h1>
          <p className="mx-auto mt-4 flex items-center justify-center gap-2 text-sm text-muted-foreground">
            <Shield className="h-4 w-4" />
            Last updated: April 08, 2025
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="mx-auto max-w-3xl px-4 pb-24 sm:px-6 lg:px-8">
        {/* Intro */}
        <div className="rounded-2xl border border-border/50 bg-surface p-8 md:p-10">
          <div className="space-y-4 leading-relaxed text-muted-foreground">
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy.
            </p>
          </div>
        </div>

        <div className="mt-10 space-y-10">
          {sections.map((section) => (
            <div
              key={section.title}
              className="rounded-2xl border border-border/50 bg-surface p-8 md:p-10"
            >
              <h2 className="text-xl font-bold tracking-tight text-foreground sm:text-2xl">
                {section.title}
              </h2>
              {section.content && (
                <div className="mt-5 space-y-4 leading-relaxed text-muted-foreground">
                  {renderBlocks(section.content)}
                </div>
              )}
              {section.subsections && (
                <div className="mt-6 space-y-8">
                  {section.subsections.map((sub) => (
                    <div key={sub.title}>
                      <h3 className="text-base font-semibold text-foreground sm:text-lg">
                        {sub.title}
                      </h3>
                      <div className="mt-3 space-y-4 leading-relaxed text-muted-foreground">
                        {renderBlocks(sub.content)}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Contact CTA */}
        <div className="mt-10 rounded-2xl border border-border/50 bg-surface p-8 md:p-10">
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            Questions About This Policy?
          </h2>
          <p className="mt-3 leading-relaxed text-muted-foreground">
            If you have any questions or concerns regarding this Privacy Policy,
            feel free to reach out to us. We&apos;re here to help.
          </p>
          <div className="mt-6 flex flex-wrap gap-3">
            <Link
              to="/contact"
              className="inline-flex items-center justify-center rounded-lg bg-cta px-5 py-2.5 text-sm font-semibold text-cta-foreground transition-all hover:bg-cta/90 hover:shadow-lg hover:shadow-cta/25"
            >
              Contact Us
            </Link>
            <EmailContactLink
              source="privacy"
              subject="Question about Privacy Policy"
              className="inline-flex items-center justify-center gap-2 rounded-lg border border-border bg-background px-5 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-surface"
            >
              <Mail className="h-4 w-4" />
              Email Us
            </EmailContactLink>
          </div>
        </div>
      </section>
    </div>
  );
}
