/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignDevelopmentRouteImport } from './routes/web-design-development'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoDigitalMarketingRouteImport } from './routes/seo-digital-marketing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OurWorksRouteImport } from './routes/our-works'
import { Route as CustomPortalsSoftwareRouteImport } from './routes/custom-portals-software'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CareMaintenanceRouteImport } from './routes/care-maintenance'
import { Route as BrandingGraphicDesignRouteImport } from './routes/branding-graphic-design'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomationAiServicesRouteImport } from './routes/automation-ai-services'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as OurWorksCaseStudyIdRouteImport } from './routes/our-works.$caseStudyId'
import { Route as InternalQuarterlyAddonsRouteImport } from './routes/internal.quarterly-addons'
import { Route as InternalArchitectureRouteImport } from './routes/internal.architecture'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WebDesignDevelopmentRoute = WebDesignDevelopmentRouteImport.update({
  id: '/web-design-development',
  path: '/web-design-development',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoDigitalMarketingRoute = SeoDigitalMarketingRouteImport.update({
  id: '/seo-digital-marketing',
  path: '/seo-digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorksRoute = OurWorksRouteImport.update({
  id: '/our-works',
  path: '/our-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomPortalsSoftwareRoute = CustomPortalsSoftwareRouteImport.update({
  id: '/custom-portals-software',
  path: '/custom-portals-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CareMaintenanceRoute = CareMaintenanceRouteImport.update({
  id: '/care-maintenance',
  path: '/care-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingGraphicDesignRoute = BrandingGraphicDesignRouteImport.update({
  id: '/branding-graphic-design',
  path: '/branding-graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationAiServicesRoute = AutomationAiServicesRouteImport.update({
  id: '/automation-ai-services',
  path: '/automation-ai-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorksCaseStudyIdRoute = OurWorksCaseStudyIdRouteImport.update({
  id: '/$caseStudyId',
  path: '/$caseStudyId',
  getParentRoute: () => OurWorksRoute,
} as any)
const InternalQuarterlyAddonsRoute = InternalQuarterlyAddonsRouteImport.update({
  id: '/internal/quarterly-addons',
  path: '/internal/quarterly-addons',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalArchitectureRoute = InternalArchitectureRouteImport.update({
  id: '/internal/architecture',
  path: '/internal/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation-ai-services': typeof AutomationAiServicesRoute
  '/blog': typeof BlogRouteWithChildren
  '/branding-graphic-design': typeof BrandingGraphicDesignRoute
  '/care-maintenance': typeof CareMaintenanceRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/custom-portals-software': typeof CustomPortalsSoftwareRoute
  '/our-works': typeof OurWorksRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/seo-digital-marketing': typeof SeoDigitalMarketingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/internal/architecture': typeof InternalArchitectureRoute
  '/internal/quarterly-addons': typeof InternalQuarterlyAddonsRoute
  '/our-works/$caseStudyId': typeof OurWorksCaseStudyIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation-ai-services': typeof AutomationAiServicesRoute
  '/blog': typeof BlogRouteWithChildren
  '/branding-graphic-design': typeof BrandingGraphicDesignRoute
  '/care-maintenance': typeof CareMaintenanceRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/custom-portals-software': typeof CustomPortalsSoftwareRoute
  '/our-works': typeof OurWorksRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/seo-digital-marketing': typeof SeoDigitalMarketingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/internal/architecture': typeof InternalArchitectureRoute
  '/internal/quarterly-addons': typeof InternalQuarterlyAddonsRoute
  '/our-works/$caseStudyId': typeof OurWorksCaseStudyIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/automation-ai-services': typeof AutomationAiServicesRoute
  '/blog': typeof BlogRouteWithChildren
  '/branding-graphic-design': typeof BrandingGraphicDesignRoute
  '/care-maintenance': typeof CareMaintenanceRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/custom-portals-software': typeof CustomPortalsSoftwareRoute
  '/our-works': typeof OurWorksRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/seo-digital-marketing': typeof SeoDigitalMarketingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/internal/architecture': typeof InternalArchitectureRoute
  '/internal/quarterly-addons': typeof InternalQuarterlyAddonsRoute
  '/our-works/$caseStudyId': typeof OurWorksCaseStudyIdRoute
  '/reports/$id': typeof ReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/automation-ai-services'
    | '/blog'
    | '/branding-graphic-design'
    | '/care-maintenance'
    | '/career'
    | '/contact'
    | '/custom-portals-software'
    | '/our-works'
    | '/pricing'
    | '/privacy'
    | '/seo-digital-marketing'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-development'
    | '/blog/$slug'
    | '/internal/architecture'
    | '/internal/quarterly-addons'
    | '/our-works/$caseStudyId'
    | '/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/automation-ai-services'
    | '/blog'
    | '/branding-graphic-design'
    | '/care-maintenance'
    | '/career'
    | '/contact'
    | '/custom-portals-software'
    | '/our-works'
    | '/pricing'
    | '/privacy'
    | '/seo-digital-marketing'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-development'
    | '/blog/$slug'
    | '/internal/architecture'
    | '/internal/quarterly-addons'
    | '/our-works/$caseStudyId'
    | '/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/automation-ai-services'
    | '/blog'
    | '/branding-graphic-design'
    | '/care-maintenance'
    | '/career'
    | '/contact'
    | '/custom-portals-software'
    | '/our-works'
    | '/pricing'
    | '/privacy'
    | '/seo-digital-marketing'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-development'
    | '/blog/$slug'
    | '/internal/architecture'
    | '/internal/quarterly-addons'
    | '/our-works/$caseStudyId'
    | '/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutomationAiServicesRoute: typeof AutomationAiServicesRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrandingGraphicDesignRoute: typeof BrandingGraphicDesignRoute
  CareMaintenanceRoute: typeof CareMaintenanceRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  CustomPortalsSoftwareRoute: typeof CustomPortalsSoftwareRoute
  OurWorksRoute: typeof OurWorksRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SeoDigitalMarketingRoute: typeof SeoDigitalMarketingRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebDesignDevelopmentRoute: typeof WebDesignDevelopmentRoute
  InternalArchitectureRoute: typeof InternalArchitectureRoute
  InternalQuarterlyAddonsRoute: typeof InternalQuarterlyAddonsRoute
  ReportsIdRoute: typeof ReportsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design-development': {
      id: '/web-design-development'
      path: '/web-design-development'
      fullPath: '/web-design-development'
      preLoaderRoute: typeof WebDesignDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-digital-marketing': {
      id: '/seo-digital-marketing'
      path: '/seo-digital-marketing'
      fullPath: '/seo-digital-marketing'
      preLoaderRoute: typeof SeoDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-works': {
      id: '/our-works'
      path: '/our-works'
      fullPath: '/our-works'
      preLoaderRoute: typeof OurWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-portals-software': {
      id: '/custom-portals-software'
      path: '/custom-portals-software'
      fullPath: '/custom-portals-software'
      preLoaderRoute: typeof CustomPortalsSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-maintenance': {
      id: '/care-maintenance'
      path: '/care-maintenance'
      fullPath: '/care-maintenance'
      preLoaderRoute: typeof CareMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding-graphic-design': {
      id: '/branding-graphic-design'
      path: '/branding-graphic-design'
      fullPath: '/branding-graphic-design'
      preLoaderRoute: typeof BrandingGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation-ai-services': {
      id: '/automation-ai-services'
      path: '/automation-ai-services'
      fullPath: '/automation-ai-services'
      preLoaderRoute: typeof AutomationAiServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-works/$caseStudyId': {
      id: '/our-works/$caseStudyId'
      path: '/$caseStudyId'
      fullPath: '/our-works/$caseStudyId'
      preLoaderRoute: typeof OurWorksCaseStudyIdRouteImport
      parentRoute: typeof OurWorksRoute
    }
    '/internal/quarterly-addons': {
      id: '/internal/quarterly-addons'
      path: '/internal/quarterly-addons'
      fullPath: '/internal/quarterly-addons'
      preLoaderRoute: typeof InternalQuarterlyAddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/architecture': {
      id: '/internal/architecture'
      path: '/internal/architecture'
      fullPath: '/internal/architecture'
      preLoaderRoute: typeof InternalArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OurWorksRouteChildren {
  OurWorksCaseStudyIdRoute: typeof OurWorksCaseStudyIdRoute
}

const OurWorksRouteChildren: OurWorksRouteChildren = {
  OurWorksCaseStudyIdRoute: OurWorksCaseStudyIdRoute,
}

const OurWorksRouteWithChildren = OurWorksRoute._addFileChildren(
  OurWorksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutomationAiServicesRoute: AutomationAiServicesRoute,
  BlogRoute: BlogRouteWithChildren,
  BrandingGraphicDesignRoute: BrandingGraphicDesignRoute,
  CareMaintenanceRoute: CareMaintenanceRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  CustomPortalsSoftwareRoute: CustomPortalsSoftwareRoute,
  OurWorksRoute: OurWorksRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SeoDigitalMarketingRoute: SeoDigitalMarketingRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebDesignDevelopmentRoute: WebDesignDevelopmentRoute,
  InternalArchitectureRoute: InternalArchitectureRoute,
  InternalQuarterlyAddonsRoute: InternalQuarterlyAddonsRoute,
  ReportsIdRoute: ReportsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
