// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrqxfuinvlevbgttabrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhycXhmdWludmxldmJndHRhYnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5Njk0OTUsImV4cCI6MjA5ODU0NTQ5NX0.A17OPNqXyj2ouuD67vbttaR1umuemUvVDBevTtzai8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(typeof window !== "undefined" ? { storage: window.localStorage } : {}),
    persistSession: typeof window !== "undefined",
    autoRefreshToken: typeof window !== "undefined",
  }
});